/*
 **                Copyright 2013, MARVELL SEMICONDUCTOR, LTD.
 ** THIS CODE CONTAINS CONFIDENTIAL INFORMATION OF MARVELL.
 ** NO RIGHTS ARE GRANTED HEREIN UNDER ANY PATENT, MASK WORK RIGHT OR COPYRIGHT
 ** OF MARVELL OR ANY THIRD PARTY. MARVELL RESERVES THE RIGHT AT ITS SOLE
 ** DISCRETION TO REQUEST THAT THIS CODE BE IMMEDIATELY RETURNED TO MARVELL.
 ** THIS CODE IS PROVIDED "AS IS". MARVELL MAKES NO WARRANTIES, EXPRESSED,
 ** IMPLIED OR OTHERWISE, REGARDING ITS ACCURACY, COMPLETENESS OR PERFORMANCE.
 **
 ** MARVELL COMPRISES MARVELL TECHNOLOGY GROUP LTD. (MTGL) AND ITS SUBSIDIARIES,
 ** MARVELL INTERNATIONAL LTD. (MIL), MARVELL TECHNOLOGY, INC. (MTI), MARVELL
 ** SEMICONDUCTOR, INC. (MSI), MARVELL ASIA PTE LTD. (MAPL), MARVELL JAPAN K.K.
 ** (MJKK), MARVELL ISRAEL LTD. (MSIL).
 */

#include "MHALVideoProcessor.h"

#undef  LOG_TAG
#define LOG_TAG "MHALVideoProcessor"

namespace mmp {

MHALVideoProcessor::MHALVideoProcessor(MHALOmxCallbackTarget *cb_target) {
  OMX_LOGD("ENTER");
  mCallbackTarget_ = cb_target;
  memset(compName, 0x00, 64);
  sprintf(compName, "\"MHALVideoProcessor\"");
  mNumPorts_ = 2;
  OMX_LOGD("EXIT");
}

MHALVideoProcessor::~MHALVideoProcessor(){
  OMX_LOGD("ENTER");
  OMX_LOGD("EXIT");
}

const char* MHALVideoProcessor::getComponentRole() {
  return "iv_processor.yuv";
}

void MHALVideoProcessor::setGeometry(int x, int y, int width, int height) {
  OMX_LOGD("ENTER");
  OMX_LOGD("EXIT");
}

}
