LOCAL_PATH := $(TARGET_COMMON_PREBUILT_TOP)/mrvl_media_player

include $(CLEAR_VARS)
LOCAL_MODULE := libmmu
LOCAL_SRC_FILES := libmmu.so
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_SUFFIX := .so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(TARGET_OUT_SHARED_LIBRARIES)
include $(BUILD_PREBUILT)



