/*
**                Copyright 2013, MARVELL SEMICONDUCTOR, LTD.
** THIS CODE CONTAINS CONFIDENTIAL INFORMATION OF MARVELL.
** NO RIGHTS ARE GRANTED HEREIN UNDER ANY PATENT, MASK WORK RIGHT OR COPYRIGHT
** OF MARVELL OR ANY THIRD PARTY. MARVELL RESERVES THE RIGHT AT ITS SOLE
** DISCRETION TO REQUEST THAT THIS CODE BE IMMEDIATELY RETURNED TO MARVELL.
** THIS CODE IS PROVIDED "AS IS". MARVELL MAKES NO WARRANTIES, EXPRESSED,
** IMPLIED OR OTHERWISE, REGARDING ITS ACCURACY, COMPLETENESS OR PERFORMANCE.
**
** MARVELL COMPRISES MARVELL TECHNOLOGY GROUP LTD. (MTGL) AND ITS SUBSIDIARIES,
** MARVELL INTERNATIONAL LTD. (MIL), MARVELL TECHNOLOGY, INC. (MTI), MARVELL
** SEMICONDUCTOR, INC. (MSI), MARVELL ASIA PTE LTD. (MAPL), MARVELL JAPAN K.K.
** (MJKK), MARVELL ISRAEL LTD. (MSIL).
*/

#ifndef BERLIN_STRING_CONVERTOR_H
#define BERLIN_STRING_CONVERTOR_H

#include "OMX_Core.h"

namespace berlin {

class StringConvertor {
  public:
    static OMX_ERRORTYPE Unicode2UTF8(OMX_U16* pUnicodeBuf, OMX_U32 iUnicodeBufLen,
        OMX_U8* pUTF8Buf, OMX_U32& iUTF8BufLen);

    static OMX_ERRORTYPE UTF82Unicode(OMX_U8* pUTF8Buf, OMX_U32 iUTF8BufLen,
        OMX_U16* pUnicodeBuf, OMX_U32& iUnicodeBufLen);
};

}

#endif

