/*
**                Copyright 2013, MARVELL SEMICONDUCTOR, LTD.
** THIS CODE CONTAINS CONFIDENTIAL INFORMATION OF MARVELL.
** NO RIGHTS ARE GRANTED HEREIN UNDER ANY PATENT, MASK WORK RIGHT OR COPYRIGHT
** OF MARVELL OR ANY THIRD PARTY. MARVELL RESERVES THE RIGHT AT ITS SOLE
** DISCRETION TO REQUEST THAT THIS CODE BE IMMEDIATELY RETURNED TO MARVELL.
** THIS CODE IS PROVIDED "AS IS". MARVELL MAKES NO WARRANTIES, EXPRESSED,
** IMPLIED OR OTHERWISE, REGARDING ITS ACCURACY, COMPLETENESS OR PERFORMANCE.
**
** MARVELL COMPRISES MARVELL TECHNOLOGY GROUP LTD. (MTGL) AND ITS SUBSIDIARIES,
** MARVELL INTERNATIONAL LTD. (MIL), MARVELL TECHNOLOGY, INC. (MTI), MARVELL
** SEMICONDUCTOR, INC. (MSI), MARVELL ASIA PTE LTD. (MAPL), MARVELL JAPAN K.K.
** (MJKK), MARVELL ISRAEL LTD. (MSIL).
*/

/*
 *  OMX_RoleNamesMrvlExt.h
 *  The OMX_RoleNames header file extention of Marvell
 */

#ifndef OMX_ROLENAMEMRVLEXT_H
#define OMX_ROLENAMEMRVLEXT_H

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#define OMX_ROLE_SUBTITLE_DECODER_SRT "subtitle_decoder.srt"

#define OMX_ROLE_SUBTITLE_SCHEDULER_BINARY "subtitle_scheduler.binary"

#ifdef __cplusplus
}
#endif /* __cplusplus */


#endif

