/*
**                Copyright 2012, MARVELL SEMICONDUCTOR, LTD.
** THIS CODE CONTAINS CONFIDENTIAL INFORMATION OF MARVELL.
** NO RIGHTS ARE GRANTED HEREIN UNDER ANY PATENT, MASK WORK RIGHT OR COPYRIGHT
** OF MARVELL OR ANY THIRD PARTY. MARVELL RESERVES THE RIGHT AT ITS SOLE
** DISCRETION TO REQUEST THAT THIS CODE BE IMMEDIATELY RETURNED TO MARVELL.
** THIS CODE IS PROVIDED "AS IS". MARVELL MAKES NO WARRANTIES, EXPRESSED,
** IMPLIED OR OTHERWISE, REGARDING ITS ACCURACY, COMPLETENESS OR PERFORMANCE.
**
** MARVELL COMPRISES MARVELL TECHNOLOGY GROUP LTD. (MTGL) AND ITS SUBSIDIARIES,
** MARVELL INTERNATIONAL LTD. (MIL), MARVELL TECHNOLOGY, INC. (MTI), MARVELL
** SEMICONDUCTOR, INC. (MSI), MARVELL ASIA PTE LTD. (MAPL), MARVELL JAPAN K.K.
** (MJKK), MARVELL ISRAEL LTD. (MSIL).
*/


#ifndef OMX_SUBTITLE_MRVL_EXT_H
#define OMX_SUBTITLE_MRVL_EXT_H

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#include <OMX_Core.h>

typedef enum OMX_SUBTITLE_CODINGTYPE {
    OMX_SUBTITLE_CodingUnused = 0,
    OMX_SUBTITLE_CodingAutoDetect,
    OMX_SUBTITLE_CodingSRT,
    OMX_SUBTITLE_CodingMrvlExtensions = 0x6F000000,
    OMX_SUBTITLE_CodingVendorStartUnused = 0x7F000000,
    OMX_SUBTITLE_CodingMax = 0x7FFFFFFF
} OMX_SUBTITLE_CODINGTYPE;



typedef struct OMX_SUBTITLE_CHUNK {
  OMX_U64 nStartPts;
  OMX_U64 nEndPts;
  OMX_PTR cPayload;
} OMX_SUBTITLE_CHUNK;


#ifdef __cplusplus
}
#endif /* __cplusplus */


#endif
