/*
 **                Copyright 2013, MARVELL SEMICONDUCTOR, LTD.
 ** THIS CODE CONTAINS CONFIDENTIAL INFORMATION OF MARVELL.
 ** NO RIGHTS ARE GRANTED HEREIN UNDER ANY PATENT, MASK WORK RIGHT OR COPYRIGHT
 ** OF MARVELL OR ANY THIRD PARTY. MARVELL RESERVES THE RIGHT AT ITS SOLE
 ** DISCRETION TO REQUEST THAT THIS CODE BE IMMEDIATELY RETURNED TO MARVELL.
 ** THIS CODE IS PROVIDED "AS IS". MARVELL MAKES NO WARRANTIES, EXPRESSED,
 ** IMPLIED OR OTHERWISE, REGARDING ITS ACCURACY, COMPLETENESS OR PERFORMANCE.
 **
 ** MARVELL COMPRISES MARVELL TECHNOLOGY GROUP LTD. (MTGL) AND ITS SUBSIDIARIES,
 ** MARVELL INTERNATIONAL LTD. (MIL), MARVELL TECHNOLOGY, INC. (MTI), MARVELL
 ** SEMICONDUCTOR, INC. (MSI), MARVELL ASIA PTE LTD. (MAPL), MARVELL JAPAN K.K.
 ** (MJKK), MARVELL ISRAEL LTD. (MSIL).
 */

#ifndef MMP_ERRORS_H
#define MMP_ERRORS_H

namespace mmp {

typedef enum {
  MMP_NO_ERROR                  =  0,
  MMP_UNEXPECTED_ERROR          =  1,
  MMP_END_OF_STREAM             =  2,
  MMP_ERROR_IO                  =  3,
  MMP_ERROR_MALFORMED           =  4,


  MMP_PAD_ERROR_START           =  0x1000,
  MMP_PAD_LINK_WRONG_HIERARCHY,
  MMP_PAD_LINK_WAS_LINKED,
  MMP_PAD_LINK_WRONG_DIRECTION,
  MMP_PAD_LINK_NOFORMAT,
  MMP_PAD_LINK_NOSCHED,
  MMP_PAD_LINK_REFUSED,
  MMP_PAD_FLOW_NOT_LINKED,
  MMP_PAD_FLOW_FLUSHING,
  MMP_PAD_FLOW_EOS,
  MMP_PAD_FLOW_NOT_NEGOTIATED,
  MMP_PAD_FLOW_ERROR,
  MMP_PAD_FLOW_NOT_SUPPORTED,
  MMP_PAD_FLOW_BLOCKED,
} MmpError;

}

#endif
